# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "EU LABEL"
api_version = "2025-01"
client_id = "6860ad69a983c0549dc759de3b0a5cb0"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders"

[webhooks]
api_version = "2025-01"

  [webhooks.customers_data_request]
  topic = "CUSTOMERS_DATA_REQUEST"
  address = "/webhooks/customers_data_request"
  format = "json"

  [webhooks.customers_redact]
  topic = "CUSTOMERS_REDACT"
  address = "/webhooks/customers_redact"
  format = "json"

  [webhooks.shop_redact]
  topic = "SHOP_REDACT"
  address = "/webhooks/shop_redact"
  format = "json"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[extensions.app_proxy]
url = "/apps/eu-compliance-suite-2026"
subpath = "eu-compliance-suite-2026"
prefix = "apps"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
